// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0UYM8WwtWbVMvp9CXat_wpiu6R2B-uU',
    appId: '1:41383721652:web:e5c87738df569691beb5e1',
    messagingSenderId: '41383721652',
    projectId: 'myflutterapp-dde4b',
    authDomain: 'myflutterapp-dde4b.firebaseapp.com',
    storageBucket: 'myflutterapp-dde4b.appspot.com',
    measurementId: 'G-G0X6TYNNKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqhneqmatgVYWCtosEsNO0qRDgWR8aYC8',
    appId: '1:41383721652:android:9f42d8b57a7a5e53beb5e1',
    messagingSenderId: '41383721652',
    projectId: 'myflutterapp-dde4b',
    storageBucket: 'myflutterapp-dde4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCx-SZ3Ebc8Tlk_tTqJwvqu7VVdr8L9cw',
    appId: '1:41383721652:ios:1b77cf7629e38ba6beb5e1',
    messagingSenderId: '41383721652',
    projectId: 'myflutterapp-dde4b',
    storageBucket: 'myflutterapp-dde4b.appspot.com',
    iosClientId: '41383721652-21fhfkvker19r81k3f8jnq3ps9lntoh7.apps.googleusercontent.com',
    iosBundleId: 'com.mynotes.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCx-SZ3Ebc8Tlk_tTqJwvqu7VVdr8L9cw',
    appId: '1:41383721652:ios:3135cd70127c1d7cbeb5e1',
    messagingSenderId: '41383721652',
    projectId: 'myflutterapp-dde4b',
    storageBucket: 'myflutterapp-dde4b.appspot.com',
    iosClientId: '41383721652-74s235ve84r6mkdviprfio5tuaf441b5.apps.googleusercontent.com',
    iosBundleId: 'com.mynotes.myFlutterApp.RunnerTests',
  );
}
